### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by willsonJewlr** [nulrich/RCTAutoComplete#1]
I am still new to this react native community.
I did npm install --save react-native-autocomplete in the new project of react-native 0.6.0.
Added the RCTAutoComplete.xcodeproj from the nodemodule to the Libraries folder.
Couldn't find any file to link to the build phase from the library, so I just run the project.

When I do var AutoComplete = require('react-native-autocomplete');

I get an error message in the simulator 
{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}

This is the terminal error output: 

React packager ready.

[20:17:31] <START> request:/index.ios.bundle
[20:17:31] <START> find dependencies
Error: Cannot find package main file for package: /Users/willson/Project/Personal/autocompleteTest/node_modules/react-native-autocomplete
    at DependecyGraph.resolveDependency (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:229:13)
    at /Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:122:22
    at Array.forEach (native)
    at collect (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:120:25)
    at DependecyGraph.getOrderedDependencies (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:141:3)
    at /Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/packager/react-packager/src/DependencyResolver/haste/index.js:96:35
    at tryCatcher (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/node_modules/bluebird/js/main/promise.js:565:18)
    at Promise._settlePromises (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/node_modules/bluebird/js/main/promise.js:681:14)
    at Async._drainQueue (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/willson/Project/Personal/autocompleteTest/node_modules/react-native/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:358:17)

How do I use this module?
Is it still in WIP?
If you could provide some instruction, that would be great!

**Comment by nulrich** [comment]
Sorry. I know I need to re-package it to make it usable through NPM. Meanwhile you have to copy the files.

**Comment by willsonJewlr** [comment]
Thanks, it worked when I just cloned them. When you repackage them, it would be really awesome if you add props to set placeholder and a way to dismiss the suggestion box on tab on screens other than the text input box. And perhaps, some ways to customize the style is always good :)

**Comment by nulrich** [comment]
It's now a Library. I published a new version on NPM, and you can follow the README for installation. I will add more options soon ;-)
